feat:[PB-18] Criar modelos de banco de dados com typeorm
cortezcodar/aposta pull request #4
Opened 2022-11-03 22:50 UTC by cortezcodar

2022-11-04 12:46 UTC, kevingamaa commented on src/models/aposta.model.ts
> +    @PrimaryGeneratedColumn('uuid')
Aqui a coluna deve ser do tipo "decimal", exemplo: 
`@Column({ name: "valor_aposta", type: "decimal", precision: 2, scale: 2 }) `

2022-11-04 12:56 UTC, kevingamaa commented on src/models/aposta.model.ts
> +    valorDaAposta: number
Aqui a coluna deve ser do tipo "decimal", exemplo:
```typecript
@Column({
  name: "valor_aposta", 
  type: "decimal", 
  precision: 2, 
  scale: 2 
})
```

2022-11-04 12:56 UTC, kevingamaa commented on src/models/aposta.model.ts
> +    dataDaAposta: string
Essa coluna deve ser datetime, exemplo de decorator: 
 ```typescript
@Column({
    name: 'data_aposta'
    type: 'datetime',
    nullable: true,
  })
```

2022-11-04 12:56 UTC, kevingamaa commented on src/models/aposta.model.ts
> +    @UpdateDateColumn()
Colocar name da coluna no banco de dados no estilo snake_case, separando espaço com "_"

2022-11-04 12:56 UTC, kevingamaa commented on src/models/aposta.model.ts
> +    @UpdateDateColumn()
Colocar name da coluna no banco de dados no estilo snake_case, separando espaço com "_"

2022-11-04 12:56 UTC, kevingamaa commented on src/data-soucer.ts
> +import 'dotenv/config'
Essas duas importações deveriam estar no seu arquivo principal "server.ts", primeira coisa a ser importada

2022-11-04 12:56 UTC, kevingamaa commented on src/models/user.model.ts
> +    @Column({ type: 'varchar', unique: true })
Colocar name da coluna no banco de dados no estilo snake_case, separando espaço com "_"

2022-11-04 12:56 UTC, kevingamaa commented on src/models/user.model.ts
> +    @UpdateDateColumn()
Colocar name da coluna no banco de dados no estilo snake_case, separando espaço com "_"

2022-11-04 12:56 UTC, kevingamaa commented on src/models/user.model.ts
> +    @UpdateDateColumn()
Colocar name da coluna no banco de dados no estilo snake_case, separando espaço com "_".

Pode mudar o nome do campo para portugues "atualizado_em"

2022-11-04 12:56 UTC, kevingamaa commented on src/models/user.model.ts
> +    @UpdateDateColumn()
Aqui seria @CreateDateColumn() inves de updateDateColumn

2022-11-04 12:56 UTC, kevingamaa commented on src/models/aposta.model.ts
> +    @UpdateDateColumn()
aqui seria @CreateDateColumn() inves de updateDateColumn

2022-11-04 13:44 UTC, kevingamaa commented on src/models/aposta.model.ts
> +
Tá faltando a proprieta/coluna userId/user_id

2022-11-04 13:45 UTC, kevingamaa commented on src/models/aposta.model.ts
> +export class Apostas {
Aqui o nome da classe deve ser "Aposta" no singular

2022-11-04 14:14 UTC, kevingamaa commented on src/models/aposta.model.ts
> +    "criado em": Date;
Tá faltando o "_" e não precisa estar em string

2022-11-04 14:15 UTC, kevingamaa commented on src/models/user.model.ts
> +
porque tirou os atributos? o @Column é para indicar como ficaria no banco de dados e o atributo é para indicar como vai ficar no codigo

2022-11-04 14:16 UTC, kevingamaa commented on src/models/user.model.ts
> +    "criado em": Date;
remover string e colocar _

2022-11-04 14:16 UTC, kevingamaa commented on src/models/user.model.ts
> +    "atualizado_em": Date;
remover aspas(string)

2022-11-07 17:42 UTC, kevingamaa requested changes

2022-11-07 17:42 UTC, kevingamaa commented on package.json
> +        "@types/cors": "^2.8.12",
types precisa ir como devDependencies e não dependencies

2022-11-07 17:42 UTC, kevingamaa commented on src/models/aposta.model.ts
> +    @UpdateDateColumn()
Não foi resolvido

2022-11-07 17:42 UTC, kevingamaa commented on src/models/user.model.ts
> +    @UpdateDateColumn()
não foi resolvido

2022-11-07 17:42 UTC, kevingamaa commented on src/models/aposta.model.ts
> +    @Column({ name: "user_id", type: 'uuid' })
Esse id deve ser do mesmo tipo da coluna na tabela do usuario "int(11)", uuid não é tipo que está sendo usado na tabela de usuario

2022-11-07 20:46 UTC, kevinGreenlight approved these changes

2022-11-07 20:47 UTC, kevingamaa approved these changes

2022-11-08 21:34 UTC, merged